### ISSUE TITLE
Add support for Sony α9 5.0 firmware update

### ISSUE THREAD

**Issue by simonmitchell** [simonmitchell/rocc#1]
The library can no longer connect to Sony α9 cameras after the 5.0 firmware released for them, the API description files which Sony make available on the camera have changed reasonably drastically and no longer contain an array of `services` in the `X_ScalarWebAPI_DeviceInfo` of `dd.xml`:

```
<?xml version="1.0" encoding="utf-8"?>
<root xmlns="urn:schemas-upnp-org:device-1-0" xmlns:dlna="urn:schemas-dlna-org:device-1-0" xmlns:av="urn:schemas-sony-com:av">
	<specVersion>
		<major>1</major>
		<minor>0</minor>
	</specVersion>
	<device>
		<deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
		<friendlyName>ILCE-9</friendlyName>
		<manufacturer>Sony Corporation</manufacturer>
		<manufacturerURL>http://www.sony.com/</manufacturerURL>
		<modelDescription>SonyRemoteCamera</modelDescription>
		<modelName>SonyImagingDevice</modelName>
		<modelURL>http://www.sony.net/</modelURL>
		<UDN>uuid:00000000-0005-0010-8000-60f189acc029</UDN>
		<serviceList>
			<service>
				<serviceType>urn:schemas-sony-com:service:DigitalImaging:1</serviceType>
				<serviceId>urn:schemas-sony-com:serviceId:DigitalImaging</serviceId>
				<SCPDURL>/DigitalImagingDesc.xml</SCPDURL>
				<controlURL>/upnp/control/DigitalImaging</controlURL>
				<eventSubURL></eventSubURL>
			</service>
		</serviceList>
		<av:X_ScalarWebAPI_DeviceInfo xmlns:av="urn:schemas-sony-com:av">
			<av:X_ScalarWebAPI_ImagingDevice>
				<av:X_ScalarWebAPI_LiveView_URL>http://192.168.122.1:60152/liveviewstream?%211234%21%2a%3a%2a%3aimage%2fjpeg%3a%2a%21%21%21%21%21</av:X_ScalarWebAPI_LiveView_URL>
				<av:X_ScalarWebAPI_DefaultFunction>RemoteShooting</av:X_ScalarWebAPI_DefaultFunction>
			</av:X_ScalarWebAPI_ImagingDevice>
		</av:X_ScalarWebAPI_DeviceInfo>
	</device>
</root>
```

There is still reference to `X_ScalarWebAPI` so I am hopeful with a few small tweaks full-behaviour will be re-instated, but there **could** be more to it: Like Sony moving to PTP (We see reference to PTP versions in `digitalImagingDescription.xml`)

An attempt to hard-code the expected services has been made [here](https://github.com/simonmitchell/rocc/tree/temp/a9_fix) which will be going out to testers of Camrote later today! 🤞 it's as simple as this, otherwise we're looking at significant amounts of work and needing access to an α9 body, which is something I can't personally afford currently!

**Comment by simonmitchell** [comment]
An update for anyone interested: still awaiting feedback from Camrote tester!

**Comment by gswirski** [comment]
@simonmitchell, I rented out Sony a9 with 6.0 firmware and ran Wireshark on it. Looks like Sony has switched to PTP/IP. 😭 

Interestingly, I successfully connected to a6400 but no luck with RX100 VII.

**Comment by simonmitchell** [comment]
@gswirski thanks for the heads up, I was worried that might be the case! That's gonna be a pretty hefty fix then, and I'm definitely going to need to source a test device somehow 😔

The a6400 may be in the same boat as the a7iii, which is considered the same generation as the a9 but still works fine. I've had complaints about this from users on:

- a7RIV
- a9
- RX100 VII

so far

**Comment by simonmitchell** [comment]
@gswirski if you come to look at this before me, I have a few ideas on how I want to implement this!

- EventNotifier will obviously have to change to accommodate the fact that the "event" system is a two-way mechanism with PTP-IP. I was thinking of doing this by creating two protocols that different cameras could conform to. Naming and exact implementation can be picked by you if you get onto this, but these would basically look like:

```
protocol EventPollable {
    // Perhaps doesn't need any functions as the `fetchEvent` function already sits on the `Camera` protocol. This could just be so the `EventNotifier` can do type checking.
}
```

```
protocol EventEmitter {
     var eventCallback: SomeClosure? { get set }
}
```

- I also want to keep the `Event` object as similar as possible to how it is currently. Having dissected the data the a9 sends, it seems that single shooting mode is now separated out from the self-timer functionality so we may have to do a bit of "Munging" of the data to make it work. I would like to instead of allowing the user to pick from a massive list containing self-timer and bracketing options, to keep the concept of "Shooting Modes" and add "Exposure Bracketing" as a value to that enum 😊

- I think whilst we're doing this PTP stuff it may also be a good opportunity to move some more types over to enums. In particular I think `WhiteBalance.Value.mode` should now be an enum, but there may be others which are currently provided to end users as strings or ints, when an enum would be more appropriate!

**Comment by gswirski** [comment]
Agreed on points 2 and 3 (although I would keep it as lower priority until we nail down PTP/IP support).

I'm not sure I fully understand the difference between "two-way" PTP/IP and the current HTTP API. The way I see it:
* you still have regular commands issued by the app. These commands expect a series of data packets (optional) and a response (required). All of these commands are serialized on the main-loop.
* if camera status changes (either as a result of a command, or because someone fiddles with camera controls), the new state is pushed onto event-loop.
* the main difference is that in PTP/IP you don't need long polling to read events. You just listen on the socket indefinitely, and if you don't receive anything for too long, you send a ping.

Does that match your understanding of the problem? Am I missing something?

**Comment by simonmitchell** [comment]
Agreed! Definitely needs to take a back seat to the main implementation. 

So all I mean by it is that the current implementation of the `EventNotifier` continuously calls the `getEvent` function with the current API implementation. However from looking how PTP works the camera is responsible for informing us when we need to fetch an “event”. In this case it’s not really actually an “event” so to speak (by that, I mean it’s not an event in PTP speaking terms) rather it’s us calling the getAllDeviceProps (I’m not sure that’s the actual name) method! So because it’s socket based, if we want to keep the event logic separated out in `EventNotifier`, that class will have to be informed somehow that a new event should be fetched from the camera ☺️

**Comment by simonmitchell** [comment]
Closing this out in favour of tracking the progress for this in the PTP/IP project!

**Comment by qdwang** [comment]
Hi @simonmitchell , I also got the issue today when I was trying to take picture with a Sony A7C. Can I use the HTTP method to take a picture with the `av:X_ScalarWebAPI_DefaultFunction` now? Don't know how to do it... And your `a9 temp fix` link has broken.... 

Thanks~

**Comment by simonmitchell** [comment]
Hi @qdwang so sorry it took so long to reply! We discovered in the end that newer models don't use the HTTP method at all sadly, you will instead need to use PTP/IP to control the camera. This ended up resulting in a pretty major effort to get this working. Your best bet is to possibly try and use ROCC if you can at all, if not, I'd recommend checking out libgphoto2!

**Comment by mrmgrpl** [comment]
Someone find this interesting:

http://192.168.122.1:10000/sony/accessControl
http://192.168.122.1:10000/sony/camera
http://192.168.122.1:10000/sony/camera
http://192.168.122.1:10000/sony/system
http://192.168.122.1:60152/liveviewstream?%211234%21%2a%3a%2a%3aimage%2fjpeg%3a%2a%21%21%21%21%21
http://192.168.122.1:64321/http://192.168.122.1:64321/
http://192.168.122.1:64321/CdsDesc.xml
http://192.168.122.1:64321/CmsDesc.xml
http://192.168.122.1:64321/DigitalImagingDesc.xml
http://192.168.122.1:64321/DmsDesc.xml
http://192.168.122.1:64321/DmsDesc.xml
http://192.168.122.1:64321/DmsDescPush.xml
http://192.168.122.1:64321/DmsRmtDesc.xml
http://192.168.122.1:64321/ScalarWebApiDesc.xml
http://192.168.122.1:64321/XPlsDesc.xml
http://192.168.122.1:64321/dd.xml
http://192.168.122.1:64321/DLNA_camera_120.jpg
http://192.168.122.1:64321/DLNA_camera_120.png 
http://192.168.122.1:64321/DLNA_camera_48.jpg
http://192.168.122.1:64321/DLNA_camera_48.png
